spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=MYSQL;DATABASE_TO_LOWER=TRUE;CASE_INSENSITIVE_IDENTIFIERS=TRUE
    username: sa
    password: password
  flyway:
    locations: classpath:db/migration/common,classpath:db/migration/{vendor}
#  liquibase:
#    change-log: db/changelog/changelog-master.xml
  jpa:
    database: mysql
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: validate
    defer-database-initialization: false
    show-sql: true


logging:
  level:
    org:
      hibernate:
        orm:
          jdbc:
            bind: TRACE